name: Versioning

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  bump-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get current version
        id: current_version
        run: |
          version=$(git describe --tags --abbrev=0)
          echo "current_version=$version" >> $GITHUB_ENV

      - name: Determine new version
        id: new_version
        run: |
          current_version=${{ env.current_version }}
          echo "Current version: $current_version"

          # Extract major, minor, and patch parts
          IFS='.' read -r -a parts <<< "${current_version#v}"

          major=${parts[0]}
          minor=${parts[1]}
          patch=${parts[2]}

          # Determine the type of bump
          pr_title="${{ github.event.pull_request.title }}"
          pr_title_lower=$(echo "$pr_title" | tr '[:upper:]' '[:lower:]')

          if [[ "$pr_title_lower" == *patch* ]]; then
            patch=$((patch + 1))
          elif [[ "$pr_title_lower" == *minor* ]]; then
            minor=$((minor + 1))
            patch=0
          elif [[ "$pr_title_lower" == *major* ]]; then
            major=$((major + 1))
            minor=0
            patch=0
          else
            echo "No version bump detected."
            exit 0
          fi

          # Construct new version
          new_version="v$major.$minor.$patch"
          echo "New version: $new_version"
          echo "new_version=$new_version" >> $GITHUB_ENV

      - name: Create new tag
        run: |
          new_version=${{ env.new_version }}
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git tag $new_version
          git push origin $new_version

